version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - DMARC_FILES:/input:ro
      - DMARC_OUTPUT_FILES:/output
    command: parsedmarc -c /parsedmarc.ini /input/* --debug
    depends_on:
      - elasticsearch
      - grafana
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    environment:
      - discovery.type=single-node
    volumes:
      - DMARC_ELASTIC_DATA:/usr/share/elasticsearch/data
      - DMARC_ELASTIC_LOGS:/usr/share/elasticsearch/logs

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'false'

volumes:
  DMARC_FILES:
  DMARC_OUTPUT_FILES:
  DMARC_ELASTIC_DATA:
  DMARC_ELASTIC_LOGS:
